/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Assignment13;

public class App {

    public static void main(String[] args) { 
        ArrayGenerator arr1 = new ArrayGenerator();
        System.out.println(arr1);
    }
}
