/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Assignment8;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        new App();
    }
}
